export enum RouteNames {
  transaction = 'Transaction',
  home = 'Home',
  picker = 'Picker',
  transactionDetail = 'TransactionDetails',
  onboarding = 'Onboarding',
  signUp = 'SignUp',
  login = 'Login',
  pin = 'Pin',
  pokemonList = 'PokemonList',
  pokemon = 'Pokemon',
  profile = 'Profile',
  tabs = 'Tabs',
  editProfile = 'EditProfile',
}
